version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Uploading to AssetsBucket 
      - aws s3 cp --recursive ./build s3://webassetsdining-artifactsbucket-10wjurkdsjioc/ 
      - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/service-worker.js s3://webassetsdining-artifactsbucket-10wjurkdsjioc/
      - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://webassetsdining-artifactsbucket-10wjurkdsjioc/
      - aws cloudfront create-invalidation --distribution-id E2FTDDUNYTT1LQ --paths /index.html /service-worker.js

artifacts:
  files:
    - '**/*'
  base-directory: build 
